### ISSUE TITLE
[Bug]: Generates empty component.html.json everytime

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/mdx2html#3]
### What happened?

It seems that mdx2html generates .html.json files that all contain `{title: None}`. 

The code that is responsible for this is https://github.com/lenra-io/mdx2html/blob/main/lib/build.js#L42.

What should be the output .html.json file content ?

**Comment by Nesqwik** [comment]
This is a feature, not a bug.
This output .html.json should contain the metadata used to create the final page in the documentation project.
To add metadata, just export a `json` variable in the mdx. this json will generate the .html.json.
